#!/bin/sh -l


RANCHER_TOKEN="$INPUT_RANCHER_TOKEN"
RANCHER_CONTEXT="$INPUT_RANCHER_CONTEXT"
RANCHER_URL="$INPUT_RANCHER_URL"

rancher login --token RANCHER_TOKEN --context RANCHER_CONTEXT RANCHER_URL
rancher kubectl $*
