  
name: Rancher CLI Action
description: Use the Rancher CLI to manage resources inside an action.
author: colbyhill21
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  token:
    description: Rancher Token for logging in.
    required: true
  context:
    description: Context of the project to access. (AKA Project ID)
    required: true
  url:
    description: URL of the Rancher instance.
    required: true
  args:
    description: Command you want to run. 
    required: true
runs:
  using: docker
  image: Dockerfile
